AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: OpenTee stack

Parameters:
  Environment:
    Type: String
    Description: specifies environment stage (local, dev, prod)
    Default: dev
  AuthPassword:
    Type: String
    Description: used as basic authentication password for lambda APIs
    Default: admin

Globals:
  Function:
    Handler: bootstrap
    Runtime: provided.al2023
    Architectures:
      - x86_64
    Environment:
      Variables:
        ENV: !Ref Environment

Resources:
  OpenTeeApi:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: OpenTeeApi
      CodeUri: cmd/api-lambda
      Timeout: 5
      MemorySize: 128
      Events:
        Health:
          Type: Api
          Properties:
            Method: GET
            Path: /opentee/health
        TeeTimeSearch:
          Type: Api
          Properties:
            Method: POST
            Path: /opentee/tee-time-search
      Environment:
        Variables:
          PASSWORD: !Ref AuthPassword
      Policies:
        - Statement:
            - Sid: DynamoAccess
              Effect: Allow
              Action:
                - "dynamodb:GetItem"
                - "dynamodb:PutItem"
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/appState"
            - Sid: EmailAccess
              Effect: Allow
              Action:
                - "ses:SendEmail"
                - ses:SendRawEmail
              Resource: !Sub arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/praisedformula5@gmail.com

  OpenTeeScheduler:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: OpenTeeScheduler
      CodeUri: cmd/scheduler-lambda
      Timeout: 5
      MemorySize: 128
      Events:
        OpenTeeUpdate:
          Type: Schedule
          Properties:
            Name: OpenTeeUpdate
            Schedule: rate(5 minutes)
            Enabled: false

Outputs:
  OpenTeeApiFunctionArn:
    Description: "ARN of the OpenTeeApi Lambda function"
    Value: !GetAtt OpenTeeApi.Arn
  OpenTeeSchedulerFunctionArn:
    Description: "ARN of the OpenTeeScheduler Lambda function"
    Value: !GetAtt OpenTeeScheduler.Arn
  OpenTeeApiEndpoint:
    Description: "API Gateway endpoint for OpenTeeApi"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/opentee/"
    Export:
      Name: !Sub "${AWS::StackName}-OpenTeeApiEndpoint"
